const CREATE_USER_NAME = 'CREATE_USER_NAME';
const FETCHED_ARTICLES = 'FETCHED_ARTICLES';
const FETCHED_COMMENTS = 'FETCHED_COMMENTS';
const VOTE = 'VOTE';

export {
    CREATE_USER_NAME,
    FETCHED_ARTICLES,
    FETCHED_COMMENTS,
    VOTE
}