const CREATE_USER_NAME = 'CREATE_USER_NAME';
const FETCHED_ARTICLES = 'FETCHED_ARTICLES';
const FETCHED_ARTICLE_COMMENTS = 'FETCHED_ARTICLE_COMMENTS';
const FETCHED_NESTED_COMMENTS = 'FETCHED_NESTED_COMMENTS';
const VOTE_NESTED_COMMENT = 'VOTE_NESTED_COMMENT';
const VOTE_COMMENT = 'VOTE_COMMENT';
const VOTE_ARTICLE = 'VOTE_COMMENT';

export {
    CREATE_USER_NAME,
    FETCHED_ARTICLES,
    FETCHED_ARTICLE_COMMENTS,
    FETCHED_NESTED_COMMENTS,
    VOTE_NESTED_COMMENT,
    VOTE_COMMENT,
    VOTE_ARTICLE
}