const CREATE_USER_NAME = 'CREATE_USER_NAME';
const FETCHED_ARTICLES = 'FETCHED_ARTICLES';
const FETCHED_COMMENTS = 'FETCHED_COMMENTS';
const VOTE = 'VOTE';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const CREATE_ARTICLE = 'CREATE_ARTICLE';
const SHOW_COMMENT_FORM_MODAL = 'SHOW_COMMENT_FORM_MODAL';
const HIDE_COMMENT_FORM_MODAL = 'HIDE_COMMENT_FORM_MODAL';
const CREATE_COMMENT = 'CREATE_COMMENT';

export {
    CREATE_USER_NAME,
    FETCHED_ARTICLES,
    FETCHED_COMMENTS,
    SET_CURRENT_PAGE,
    CREATE_ARTICLE,
    VOTE,
    SHOW_COMMENT_FORM_MODAL,
    HIDE_COMMENT_FORM_MODAL,
    CREATE_COMMENT
}